### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by CoreText** [alansbraga/NPPGit#1]
Could you write about installation, please?

**Comment by alansbraga** [comment]
I updated the repository, let me know if anything is wrong.
Specially on english text.

**Comment by CoreText** [comment]
Error messages alerts:
First popup: "The program can't start because MSVCP140.dll is missing from your computer "
Second: "Plugin is not compatable with current version of Notepad++"
Thanks.

**Comment by alansbraga** [comment]
I added more info on installation process, please verify if this is enough.
