### ISSUE TITLE
NPPGit doesn't work on win10 64bit

### ISSUE THREAD

**Issue by xuzhousoft09** [alansbraga/NPPGit#6]
Hello alansbraga

I tried to install the NPPGit, but it doesn't work on my  win10 64bit computer.

I followed your instruction:
1. install the TortoiseGit.
2. install the Visual C++ Redistributable for Visual Studio 2015.
3. copy the .dll file into the 'D:\Program Files\Notepad++\plugins'.
4. restart the notepad++.

But, I couldn't find the installed NPPGit in my notepad++.

![1](https://user-images.githubusercontent.com/12077057/86889821-f61d6780-c12e-11ea-8483-9fc3ad3a3ed3.gif)

**Comment by alansbraga** [comment]
Hi, the only problem I saw in your video: Create the folder NPPGit on the plugins folder and let only the NPPGit.dll.
  
![image](https://user-images.githubusercontent.com/10046322/86916314-cdc74600-c0f9-11ea-97b5-50f0b38db897.png)

**Comment by xuzhousoft09** [comment]
Thank you!
